-- Issue #103: usage events did not record why a request was served by a
-- fallback account. When the primary account was unusable up front (cooldown
-- after upstream 429 / transport failures, or disabled), the proxy wrote a
-- single attempt row for the fallback candidate with retry_count=0, so
-- consumers could not tell "served by primary" from "primary skipped,
-- fallback served".
--
-- Persist the reason as a white-listed code generated by the data plane:
--   account_disabled / account_cooling_down / account_unhealthy /
--   account_unavailable      -- primary unusable before any request was sent
--   upstream_http_<status>   -- retryable primary response, e.g. 429
--   upstream_transport_error -- primary transport failure
-- NULL means no fallback occurred (primary succeeded / single attempt).

INSERT INTO gateway_schema_migrations (version, name)
VALUES (19, 'usage_fallback_reason')
ON CONFLICT (version) DO NOTHING;

UPDATE gateway_schema_metadata
SET schema_version = GREATEST(schema_version, 19),
    migration_version = GREATEST(migration_version, 19),
    updated_at = NOW()
WHERE singleton = TRUE;

ALTER TABLE usage_events
  ADD COLUMN IF NOT EXISTS fallback_reason TEXT;

COMMENT ON COLUMN usage_events.fallback_reason IS
  'Why the request was served by a fallback account instead of the primary; NULL when no fallback occurred. Codes: account_disabled, account_cooling_down, account_unhealthy, account_unavailable, upstream_http_<status>, upstream_transport_error.';
